Repository zxcvbn-ts/zxcvbn, pull requests merged in 2021-01, with the labels that each got.

#18 Fix browser package
  docs/guide/README.md
  packages/common/package.json
  packages/de/package.json
  packages/en/package.json
  packages/main/package.json
  scripts/rollup.config.js
Labels: bug

#19 Add documentation example
  docs/guide/LazyLoading/README.md
  docs/guide/UserInput/README.md
Labels: documentation

#17 Add new keyboard layouts
  data-scripts/keyboardLayouts/azerty.ts
  data-scripts/keyboardLayouts/qwertz.ts
  packages/main/src/data/adjacencyGraphs.ts
  packages/main/test/helper/passwordTests.ts
Labels: enhancement

#21 Add guide for new language package
  .eslintignore
  README.md
  data-scripts/_generators/KeyboardAdjacencyGraph.ts
  data-scripts/_generators/PasswordGenerator.ts
  data-scripts/_helpers/runtime.ts
  data-scripts/generate.ts
  data-scripts/lists.ts
  docs/guide/Languages/README.md
Labels: bug, documentation

#20 Dutch and Belgium
  data-scripts/_generators/ExcelGenerator.ts
  data-scripts/_helpers/runtime.ts
  data-scripts/generate.ts
  data-scripts/lists.ts
  docs/guide/Languages/README.md
  package.json
  packages/nl-be/CHANGELOG.md
  packages/nl-be/README.md
  packages/nl-be/package.json
  packages/nl-be/src/boysFirstnames.json
  packages/nl-be/src/commonWords.json
  packages/nl-be/src/girlsFirstnames.json
  packages/nl-be/src/index.ts
  packages/nl-be/src/lastnames.json
  packages/nl-be/src/translations.ts
  packages/nl-be/tsconfig.json
  yarn.lock
Labels: enhancement

#22 Improve straight row translation
  packages/de/src/translations.ts
  packages/en/src/translations.ts
  packages/main/test/helper/passwordTests.ts
Labels: enhancement
