Repository zxcvbn-ts/zxcvbn, pull requests merged in 2021-12, with the labels that each got.

#79 Add parameter to add userInputs on the fly
  packages/libraries/main/src/Options.ts
  packages/libraries/main/src/index.ts
  packages/libraries/main/src/types.ts
  packages/libraries/main/test/main.spec.ts
Labels: enhancement

#82 Spanish language pack
  data-scripts/lists.ts
  packages/languages/es-es/README.md
  packages/languages/es-es/package.json
  packages/languages/es-es/src/commonWords.json
  packages/languages/es-es/src/firstnames.json
  packages/languages/es-es/src/index.ts
  packages/languages/es-es/src/lastnames.json
  packages/languages/es-es/src/translations.ts
  packages/languages/es-es/src/wikipedia.json
  packages/languages/es-es/tsconfig.json
Labels: enhancement

#66 Add HaveIBeenPwned matcher
  docs/guide/matcher/README.md
  packages/languages/de/src/translations.ts
  packages/languages/en/src/translations.ts
  packages/languages/es-es/src/translations.ts
  packages/languages/fr/src/translations.ts
  packages/languages/nl-be/src/translations.ts
  packages/libraries/main/src/types.ts
  packages/libraries/pwned/CHANGELOG.md
  packages/libraries/pwned/README.md
  packages/libraries/pwned/package.json
  packages/libraries/pwned/src/feedback.ts
  packages/libraries/pwned/src/haveIBeenPwned.ts
  packages/libraries/pwned/src/index.ts
  packages/libraries/pwned/src/matching.ts
  packages/libraries/pwned/src/scoring.ts
  packages/libraries/pwned/test/matching.spec.ts
  packages/libraries/pwned/test/scoring.spec.ts
  packages/libraries/pwned/tsconfig.json
  tsconfig.json
Labels: enhancement

#89 Bump packages
  .eslintrc.js
  data-scripts/_generators/PasswordGenerator.ts
  package.json
  packages/libraries/main/src/Matching.ts
  packages/libraries/main/src/matcher/repeat/matching.ts
  packages/libraries/main/src/scoring/index.ts
  yarn.lock
Labels: dependencies

#90 Add es-es wikipedia dictionary
  packages/languages/es-es/src/wikipedia.json
Labels: enhancement

#92 Fixed broken link in README.md
  README.md
Labels: documentation
