Repository zxcvbn-ts/zxcvbn, pull requests merged in 2022-01, with the labels that each got.

#91 Separate async/sync into two functions (breaking-change)
  docs/guide/matcher/README.md
  packages/libraries/main/src/index.ts
  packages/libraries/main/test/asyncMatcher.spec.ts
  packages/libraries/main/test/customMatcher.spec.ts
  packages/libraries/main/test/main.spec.ts
  packages/libraries/main/test/scoring/guesses/calc.spec.ts
  packages/libraries/pwned/test/index.spec.ts
Labels: bug

#93 Add debounce helper
  README.md
  docs/.vuepress/components/ZxcvbnInteractive.vue
  docs/guide/framework-examples/README.md
  docs/guide/getting-started/README.md
  docs/guide/languages/README.md
  docs/guide/matcher/README.md
  packages/languages/de/README.md
  packages/languages/en/README.md
  packages/languages/es-es/README.md
  packages/languages/nl-be/README.md
  packages/libraries/main/README.md
  packages/libraries/main/src/debounce.ts
  packages/libraries/main/src/index.ts
  packages/libraries/main/test/debounce.spec.ts
Labels: enhancement

#95 Resolve Pwned missing translation
  docs/.vuepress/components/Comparison.vue
  docs/.vuepress/components/ZxcvbnInteractive.vue
  docs/guide/framework-examples/README.md
  docs/guide/getting-started/README.md
  docs/guide/languages/README.md
  docs/guide/lazy-loading/README.md
  docs/guide/matcher/README.md
  docs/guide/migration/README.md
  docs/guide/user-input/README.md
  packages/languages/common/README.md
  packages/languages/de/README.md
  packages/languages/en/README.md
  packages/languages/es-es/README.md
  packages/languages/nl-be/README.md
  packages/libraries/main/CHANGELOG.md
  packages/libraries/main/README.md
  packages/libraries/main/src/Feedback.ts
  packages/libraries/main/src/Matching.ts
  packages/libraries/main/src/Options.ts
  packages/libraries/main/src/TimeEstimates.ts
  packages/libraries/main/src/data/translationKeys.ts
  packages/libraries/main/src/index.ts
  packages/libraries/main/src/matcher/date/feedback.ts
  packages/libraries/main/src/matcher/dictionary/feedback.ts
  packages/libraries/main/src/matcher/dictionary/matching.ts
  packages/libraries/main/src/matcher/dictionary/variants/matching/l33t.ts
  packages/libraries/main/src/matcher/regex/feedback.ts
  packages/libraries/main/src/matcher/repeat/feedback.ts
  packages/libraries/main/src/matcher/sequence/feedback.ts
  packages/libraries/main/src/matcher/spatial/feedback.ts
  packages/libraries/main/src/matcher/spatial/matching.ts
  packages/libraries/main/src/matcher/spatial/scoring.ts
  packages/libraries/main/src/scoring/estimate.ts
  packages/libraries/main/test/asyncMatcher.spec.ts
  packages/libraries/main/test/customMatcher.spec.ts
  packages/libraries/main/test/main.spec.ts
  packages/libraries/pwned/README.md
  packages/libraries/pwned/package.json
  packages/libraries/pwned/src/feedback.ts
  packages/libraries/pwned/src/index.ts
  packages/libraries/pwned/test/index.spec.ts
  packages/libraries/pwned/test/matching.spec.ts
  scripts/rollup.config.js
Labels: bug

#97 docs: Improve phrasing and formatting, and correct some errors
  docs/guide/languages/README.md
Labels: documentation

#98 feat(language): add Italian translation
  data-scripts/lists.ts
  packages/languages/it/CHANGELOG.md
  packages/languages/it/README.md
  packages/languages/it/package.json
  packages/languages/it/src/commonWords.json
  packages/languages/it/src/firstnames.json
  packages/languages/it/src/index.ts
  packages/languages/it/src/lastnames.json
  packages/languages/it/src/translations.ts
  packages/languages/it/src/wikipedia.json
  packages/languages/it/tsconfig.json
Labels: enhancement

#99 feat: adding support to pt-br language
  data-scripts/_generators/ApiGenerator.ts
  data-scripts/_generators/HTMLGenerator.ts
  data-scripts/lists.ts
  packages/languages/pt-br/CHANGELOG.md
  packages/languages/pt-br/README.md
  packages/languages/pt-br/package.json
  packages/languages/pt-br/src/commonWords.json
  packages/languages/pt-br/src/firstnames.json
  packages/languages/pt-br/src/index.ts
  packages/languages/pt-br/src/lastnames.json
  packages/languages/pt-br/src/translations.ts
  packages/languages/pt-br/src/wikipedia.json
  packages/languages/pt-br/tsconfig.json
Labels: enhancement
