Repository zxcvbn-ts/zxcvbn, pull requests merged in 2022-12, with the labels that each got.

#151 Update dependencies
  .eslintignore
  .nvmrc
  jest.config.js
  package.json
  packages/libraries/main/test/asyncMatcher.spec.ts
  scripts/jsonPlugin.mjs
  scripts/rollup.config.mjs
  yarn.lock
Labels: enhancement

#153 docs(project): add react framework example
  docs/guide/framework-examples/README.md
Labels: documentation

#156 (fix) prefer primitive boolean over Boolean
  docs/guide/options/README.md
  packages/libraries/main/src/Feedback.ts
  packages/libraries/main/src/matcher/dictionary/feedback.ts
  packages/libraries/main/src/types.ts
Labels: bug

#157 Add type ban eslint rule
  .eslintrc.js
  data-scripts/_generators/ApiGenerator.ts
  data-scripts/_generators/HTMLGenerator.ts
  data-scripts/_generators/SimpleListGenerator.ts
  data-scripts/lists.ts
  data-scripts/wikiExtractor/index.ts
  packages/libraries/main/src/matcher/dictionary/matching.ts
  packages/libraries/main/src/matcher/dictionary/types.ts
  packages/libraries/main/src/matcher/dictionary/variants/matching/l33t.ts
  packages/libraries/main/src/matcher/dictionary/variants/matching/reverse.ts
  packages/libraries/main/src/scoring/index.ts
  packages/libraries/pwned/src/haveIBeenPwned.ts
  packages/libraries/pwned/src/index.ts
  packages/libraries/pwned/src/matching.ts
  packages/libraries/pwned/src/types.ts
  packages/libraries/pwned/test/index.spec.ts
  packages/libraries/pwned/test/matching.spec.ts
Labels: enhancement
