Repository zxcvbn-ts/zxcvbn, pull requests merged in 2023-02, with the labels that each got.

#173 Make debounce third parameter optional and add docu
  docs/guide/README.md
  docs/guide/examples/README.md
  docs/guide/framework-examples/README.md
  docs/guide/options/README.md
  docs/guide/user-input/README.md
  packages/libraries/main/src/debounce.ts
Labels: bug, documentation

#174 Resolve issue with max stack size
  packages/libraries/main/src/Options.ts
Labels: bug

#176 chore!: make language packages tree shakeable
  data-scripts/_helpers/runtime.ts
  docs/.vuepress/components/Comparison.vue
  docs/.vuepress/components/ZxcvbnInteractive.vue
  docs/guide/framework-examples/README.md
  docs/guide/getting-started/README.md
  docs/guide/languages/README.md
  docs/guide/migration/README.md
  packages/languages/common/README.md
  packages/languages/common/src/index.ts
  packages/languages/de/README.md
  packages/languages/de/src/index.ts
  packages/languages/en/README.md
  packages/languages/en/src/index.ts
  packages/languages/es-es/README.md
  packages/languages/es-es/src/index.ts
  packages/languages/fi/README.md
  packages/languages/fi/src/index.ts
  packages/languages/fr/README.md
  packages/languages/fr/src/index.ts
  packages/languages/id/README.md
  packages/languages/id/src/index.ts
  packages/languages/it/README.md
  packages/languages/it/src/index.ts
  packages/languages/ja/README.md
  packages/languages/ja/src/index.ts
  packages/languages/nl-be/README.md
  packages/languages/nl-be/src/index.ts
  packages/languages/pl/README.md
  packages/languages/pl/src/index.ts
  packages/languages/pt-br/README.md
  packages/languages/pt-br/src/index.ts
  packages/libraries/main/test/asyncMatcher.spec.ts
  packages/libraries/main/test/customMatcher.spec.ts
  packages/libraries/main/test/levenshtein.spec.ts
  packages/libraries/main/test/main.spec.ts
  packages/libraries/main/test/matcher/dictionary/matching.spec.ts
  packages/libraries/main/test/matcher/spatial/matching.spec.ts
  packages/libraries/main/test/matcher/spatial/scoring.spec.ts
  packages/libraries/main/test/matching.spec.ts
Labels: enhancement

#177 Remove default exports
  data-scripts/_generators/PasswordGenerator.ts
  docs/.vuepress/components/ZxcvbnInteractive.vue
  packages/libraries/main/src/Feedback.ts
  packages/libraries/main/src/Matching.ts
  packages/libraries/main/src/Options.ts
  packages/libraries/main/src/TimeEstimates.ts
  packages/libraries/main/src/index.ts
  packages/libraries/main/src/matcher/date/feedback.ts
  packages/libraries/main/src/matcher/dictionary/feedback.ts
  packages/libraries/main/src/matcher/dictionary/matching.ts
  packages/libraries/main/src/matcher/dictionary/variants/matching/l33t.ts
  packages/libraries/main/src/matcher/regex/feedback.ts
  packages/libraries/main/src/matcher/repeat/feedback.ts
  packages/libraries/main/src/matcher/sequence/feedback.ts
  packages/libraries/main/src/matcher/spatial/feedback.ts
  packages/libraries/main/src/matcher/spatial/matching.ts
  packages/libraries/main/src/matcher/spatial/scoring.ts
  packages/libraries/main/src/scoring/estimate.ts
  packages/libraries/main/test/feedback.spec.ts
  packages/libraries/main/test/matcher/dictionary/matching.spec.ts
  packages/libraries/main/test/matcher/dictionary/variant/matching/dictionaryReverse.spec.ts
  packages/libraries/main/test/matcher/dictionary/variant/matching/l33t.spec.ts
  packages/libraries/main/test/matcher/repeat/matching.spec.ts
  packages/libraries/main/test/matcher/repeat/scoring.spec.ts
  packages/libraries/main/test/matcher/spatial/matching.spec.ts
  packages/libraries/main/test/matcher/spatial/scoring.spec.ts
  packages/libraries/main/test/matching.spec.ts
  packages/libraries/main/test/options.spec.ts
  packages/libraries/main/test/scoring/search.spec.ts
  packages/libraries/main/test/timeEstimates.spec.ts
  packages/libraries/pwned/src/index.ts
  packages/libraries/pwned/test/index.spec.ts
  packages/libraries/pwned/test/matching.spec.ts
Labels: enhancement

#178 Add network error handler option
  packages/libraries/main/src/Matching.ts
  packages/libraries/pwned/src/haveIBeenPwned.ts
  packages/libraries/pwned/src/index.ts
  packages/libraries/pwned/src/matching.ts
  packages/libraries/pwned/src/types.ts
Labels: enhancement

#180 Add compound splitter
  data-scripts/_generators/ApiGenerator.ts
  data-scripts/_generators/ExcelGenerator.ts
  data-scripts/_generators/HTMLGenerator.ts
  data-scripts/_generators/SimpleListGenerator.ts
  data-scripts/_generators/TxtGenerator.ts
  data-scripts/lists.ts
  packages/languages/es-es/src/firstnames.json
  packages/languages/es-es/src/index.ts
Labels: enhancement

#179 Add diceware dictionary
  docs/guide/matcher/README.md
  packages/languages/common/src/diceware.json
  packages/languages/common/src/index.ts
  packages/libraries/main/src/matcher/dictionary/scoring.ts
  packages/libraries/main/test/matcher/dictionary/scoring.spec.ts
Labels: enhancement
