Repository zxcvbn-ts/zxcvbn, pull requests merged in 2023-01, with the labels that each got.

#155 Use correct type imports path
  .github/workflows/lint.js.yml
  packages/libraries/main/src/index.ts
  packages/libraries/main/test/scoring/guesses/calc.spec.ts
  packages/libraries/pwned/src/feedback.ts
  packages/libraries/pwned/src/index.ts
  packages/libraries/pwned/src/matching.ts
Labels: bug

#160 Update packages
  data-scripts/_generators/ApiGenerator.ts
  data-scripts/_generators/ExcelGenerator.ts
  data-scripts/_generators/HTMLGenerator.ts
  data-scripts/_generators/SimpleListGenerator.ts
  data-scripts/_generators/TxtGenerator.ts
  data-scripts/_helpers/runtime.ts
  data-scripts/lists.ts
  package.json
  packages/languages/pt-br/src/lastnames.json
  yarn.lock
Labels: enhancement

#161 Docs: Add missing default for adjacencyGraphs
  docs/guide/lazy-loading/README.md
Labels: documentation

#165 Resolve dos
  packages/libraries/main/src/Options.ts
  packages/libraries/main/src/matcher/dictionary/matching.ts
  packages/libraries/main/src/matcher/dictionary/variants/matching/l33t.ts
  packages/libraries/main/src/types.ts
  packages/libraries/main/test/main.spec.ts
  packages/libraries/main/test/matcher/dictionary/variant/matching/l33t.spec.ts
Labels: bug

#167 Limit the used password string length to prevent redos attacks
  packages/libraries/main/src/Options.ts
  packages/libraries/main/src/index.ts
  packages/libraries/main/src/types.ts
  packages/libraries/main/test/main.spec.ts
Labels: bug

#166 docs(custom-matcher): add description about properties
  docs/guide/matcher/README.md
  packages/libraries/main/src/types.ts
Labels: documentation
