Repository zxcvbn-ts/zxcvbn, pull requests merged in 2024-02, with the labels that each got.

#251 Wrong type code in React example code
  docs/guide/framework-examples/README.md
Labels: documentation

#249 Language specific dictionaries
  data-scripts/_helpers/runtime.ts
  packages/languages/ar/src/index.ts
  packages/languages/cs/src/index.ts
  packages/languages/de/src/index.ts
  packages/languages/en/src/index.ts
  packages/languages/es-es/src/index.ts
  packages/languages/fi/src/index.ts
  packages/languages/fr/src/index.ts
  packages/languages/id/src/index.ts
  packages/languages/it/src/index.ts
  packages/languages/ja/src/index.ts
  packages/languages/nl-be/src/index.ts
  packages/languages/pl/src/index.ts
  packages/languages/pt-br/src/index.ts
  packages/libraries/main/src/matcher/dictionary/feedback.ts
  packages/libraries/main/src/types.ts
  packages/libraries/main/test/helper/passwordTests.ts
  packages/libraries/main/test/matcher/dictionary/matching.spec.ts
Labels: bug

#250 Make scoring thresholds configurable
  docs/.vuepress/components/Result.vue
  docs/guide/getting-started/README.md
  docs/guide/migration/README.md
  docs/guide/options/README.md
  packages/libraries/main/src/Options.ts
  packages/libraries/main/src/TimeEstimates.ts
  packages/libraries/main/src/types.ts
  packages/libraries/main/test/customMatcher.spec.ts
  packages/libraries/main/test/helper/passwordTests.ts
  packages/libraries/main/test/main.spec.ts
  packages/libraries/main/test/timeEstimates.spec.ts
  packages/libraries/main/test/utils/levenshtein.spec.ts
  packages/libraries/pwned/test/index.spec.ts
Labels: enhancement
